<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\LoginAsCustomer\Model;

use Magento\Store\Api\Data\StoreInterface;

/**
 * Class FrontendUrl
 */
class FrontendUrlBuilder
{
    /**
     * @var \Magento\Framework\UrlInterface
     */
    private $url;

    public function __construct(
        \Magento\Framework\UrlInterface $url
    ) {
        $this->url = $url;
    }

    /**
     * @param StoreInterface $store
     */
    public function setStore(StoreInterface $store)
    {
        $this->url->setScope($store);
    }

    /**
     * @param   string|null $routePath
     * @param   array|null $routeParams
     *
     * @return string
     */
    public function buildUrl($routePath = null, $routeParams = null)
    {
        return $this->url->getUrl($routePath, $routeParams);
    }
}
