<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\LoginAsCustomer\Model;

/**
 * Class HashGeneratorInterface
 */
interface HashGeneratorInterface
{
    /**
     * Get random string.
     *
     * @param int $length
     * @param null|string $chars
     *
     * @return string
     */
    public function generateHash($length, $chars = null);
}
