<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\LoginAsCustomer\Model;

use Magento\Framework\Math\Random;

class HashGenerator implements HashGeneratorInterface
{
    /**
     * @var Random
     */
    private $generator;

    public function __construct(
        Random $generator
    ) {
        $this->generator = $generator;
    }

    /**
     * @inheritDoc
     */
    public function generateHash($length, $chars = null) : string
    {
        return $this->generator->getRandomString($length, $chars);
    }
}
