<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\LoginAsCustomer\Model;

use Magento\Customer\Model\Customer;
use Magento\Framework\Event\ManagerInterface;

/**
 * Class LoginProcessor
 *
 * Login processor model class.
 */
class LoginProcessor implements LoginProcessorInterface
{
    /**
     * @var ManagerInterface
     */
    private $eventManager;

    /**
     * @var \Magento\Framework\Message\ManagerInterface
     */
    private $messageManager;

    /**
     * @var AuthenticatorInterface
     */
    private $authenticator;

    public function __construct(
        \MagedIn\LoginAsCustomer\Model\AuthenticatorInterface $authenticator,
        ManagerInterface $eventManager,
        \Magento\Framework\Message\ManagerInterface $messageManager
    ) {
        $this->eventManager = $eventManager;
        $this->messageManager = $messageManager;
        $this->authenticator = $authenticator;
    }

    /**
     * @inheritDoc
     */
    public function process(int $customerId, int $adminUserId) : ?Customer
    {
        /** @var Customer $customer */
        $customer = $this->authenticator->authenticate($customerId, $adminUserId);

        if (!$customer || !$customer->getId()) {
            $this->eventManager->dispatch('magedin_login_as_customer_fail', [
                'customer_id'   => $customerId,
                'admin_user_id' => $adminUserId
            ]);

            return null;
        }

        $this->eventManager->dispatch('magedin_login_as_customer_success', [
            'customer'      => $customer,
            'admin_user_id' => $adminUserId
        ]);

        return $customer;
    }
}
