<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\LoginAsCustomer\Model;

use Magento\Framework\AuthorizationInterface;

class Permission
{
    /**
     * @var Config
     */
    private $config;

    /**
     * @var AuthorizationInterface
     */
    private $authorization;

    public function __construct(
        Config $config,
        AuthorizationInterface $authorization
    ) {
        $this->config = $config;
        $this->authorization = $authorization;
    }

    /**
     * @return bool
     */
    public function allowLoginAsCustomer() : bool
    {
        if (!$this->config->isEnabled()) {
            return false;
        }

        if (!$this->authorization->isAllowed('MagedIn_LoginAsCustomer::login_button')) {
            return false;
        }

        return true;
    }
}
