<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\LoginAsCustomer\Model;

/**
 * Class UrlParametersEncryptorInterface
 */
interface UrlParametersEncryptorInterface
{
    /**
     * @param array $parameters
     *
     * @return string|null
     */
    public function encrypt(array $parameters) : ?string;

    /**
     * @param string $hash
     *
     * @return array|null
     */
    public function decrypt(string $hash) : ?array;
}
