<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */
declare(strict_types=1);

namespace MagedIn\LoginAsCustomer\Model\Validator;

use Magento\Customer\Model\ResourceModel\Customer;

/**
 * Class CustomerIdValidator
 *
 * Customer identifier validator model class.
 */
class CustomerIdValidator
{
    /**
     * @var Customer
     */
    private $customerResource;

    public function __construct(
        Customer $customerResource
    ) {
        $this->customerResource = $customerResource;
    }

    /**
     * @param int $customerId
     *
     * @return bool
     */
    public function validate(int $customerId) : bool
    {
        if (!$customerId) {
            return false;
        }

        if (!$this->customerResource->checkCustomerId($customerId)) {
            return false;
        }

        return true;
    }
}
