<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\LoginAsCustomer\Model\Validator;

/**
 * Class ExpirationTimeValidator
 *
 * Expiration time validator model class.
 */
class ExpirationTimeValidator
{
    /**
     * @param string $time
     *
     * @return bool
     */
    public function validate(string $time) : bool
    {
        $expiresAt = strtotime($time);
        $now = strtotime('now');
        $difference = $expiresAt - $now;

        if ($difference < 0) {
            return false;
        }

        return true;
    }
}
