<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\LoginAsCustomer\Block\Html\Advisor;

/**
 * Class TopHeader
 *
 * Advisor top header block class.
 */
class TopHeader extends \Magento\Framework\View\Element\Template
{
}
