<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */
declare(strict_types=1);

namespace MagedIn\LoginAsCustomer\Controller;

use MagedIn\LoginAsCustomer\Model\Config;
use MagedIn\LoginAsCustomer\Model\Config\Source\CustomerRedirectOptions;
use Magento\Framework\App\Response\RedirectInterface;
use Magento\Framework\App\ResponseInterface;

class CustomerRedirector implements CustomerRedirectorInterface
{
    /**
     * @var RedirectInterface
     */
    private $redirect;

    /**
     * @var ResponseInterface
     */
    private $response;

    /**
     * @var Config
     */
    private $config;

    public function __construct(
        ResponseInterface $response,
        Config $config,
        RedirectInterface $redirect
    ) {
        $this->redirect = $redirect;
        $this->config = $config;
        $this->response = $response;
    }

    /**
     * @param array $arguments
     *
     * @return ResponseInterface
     */
    public function redirectOnSuccess(array $arguments = []) : ResponseInterface
    {
        $urlPath = $this->config->getRedirectAfterLogin();

        if (empty($urlPath)) {
            $urlPath = CustomerRedirectOptions::URL_PATH_CUSTOMER_ACCOUNT;
        }

        return $this->redirect($urlPath, $arguments);
    }

    /**
     * @param array $arguments
     *
     * @return ResponseInterface
     */
    public function redirectOnFail(array $arguments = []) : ResponseInterface
    {
        return $this->redirectToLogin($arguments);
    }

    /**
     * @param array $arguments
     *
     * @return ResponseInterface
     */
    private function redirectToLogin(array $arguments = []) : ResponseInterface
    {
        return $this->redirect(CustomerRedirectOptions::URL_PATH_CUSTOMER_LOGIN, $arguments);
    }

    /**
     * @param string $path
     * @param array  $arguments
     *
     * @return ResponseInterface
     */
    private function redirect(string $path, $arguments = []) : ResponseInterface
    {
        $this->redirect->redirect($this->response, $path, $arguments);
        return $this->response;
    }
}
